version: '3.7'

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER}
    image: postgres:15-alpine
#    volumes:
#      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"  ]
      interval: 10s
      timeout: 30s
      retries: 3

networks:
  default:
    name: jet_industries_network
