server:
  port: 8080
  servlet:
    context-path: /jet-industries
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jetindustries
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
